Bug Fix: Error: Value for unconfigurable attribute
When running this code as is I get an error:

```
Error: Value for unconfigurable attribute
│ 
│   with aws_eip.nat_gateway_eip,
│   on main.tf line 108, in resource "aws_eip" "nat_gateway_eip":
│  108:   domain     = "vpc"
```

I updated the line to the property which was used in the course video, which was:
vpc = true